package example;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.tws.refactoring.Driver;
import com.tws.refactoring.Police;
import org.junit.jupiter.api.*;

import java.util.LinkedList;
import java.util.List;

import static java.time.Duration.ofMillis;
import static org.junit.jupiter.api.Assertions.*;



class PoliceTest {
    @Test
    public void shoud_driver_age_19_return_true(){
        //given
        Driver driver = new Driver(19);
        Police police = new Police();
        //when
        Boolean b = police.checkDriver(driver);
        //then
        assertEquals(true,b);
    }
    @Test
    public void shoud_driver_age7_return_false(){
        //given
        Driver driver = new Driver(17);
        Police police = new Police();
        //when
        Boolean b = police.checkDriver(driver);
        //then
        assertEquals(false,b);
    }


}
